databases:
  - name: poemsproject
    databaseName: bearabookdb
    user: bearabookdb_user

services:
  - type: web
    name: poemsproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn poemsproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poemsproject
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4