# Generated by Django 4.2.2 on 2023-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_alter_poem_author_alter_poem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='excerpt',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
