# Generated by Django 4.2.2 on 2023-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_poem_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
