# Generated by Django 4.2.2 on 2023-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_poem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(null=True, upload_to='poems_images/'),
        ),
    ]
